import {
    Check,
    ChevronLeft,
    ChevronRight,
    FileCheck2,
    UserRound,
    Smartphone,
    Users,
    Landmark,
    ClipboardCheck,
    AlertCircle,
    ShieldCheck,
    Sparkles,
    CircleCheck,
    Wallet,
    Clock,
    BadgeCheck,
    Fingerprint,
    Calendar,
    Phone,
    Mail,
    MapPin,
    User,
    Building2,
    CreditCard,
    UserPlus,
    Handshake,
} from "lucide-react";
export const steps = [
        {
            number: 1,
            title: "Customer Details",
            description: "Personal details",
            icon: UserRound,
        },
        {
            number: 2,
            title: "Linked Phone",
            description: "Mobile numbers",
            icon: Smartphone,
        },
        {
            number: 3,
            title: "Services",
            description: "Select services",
            icon: Wallet,
        },
        {
            number: 4,
            title: "Declaration",
            description: "Confirm & submit",
            icon: ClipboardCheck,
        },
    ];